a, b, c, d, e, f=input().split()
a=float(a)
b=float(b)
c=float(c)
d=float(d)
e=float(e)
f=float(f)
J1=(a-b)*(c/d)-(e+f)
print("%.3f\n" %J1)

A1, B1=input().split()
C1, D1=input().split()
E1, F1=input().split()
A1=float(A1)
B1=float(B1)
C1=float(C1)
D1=float(D1)
E1=float(E1)
F1=float(F1)
J2=(A1-B1)*(C1/D1)-(E1+F1)
print("%.3f\n" %J2)